(define (problem problemav2)
  (:domain robot-limpieza)
  (:objects r1 - robot aula1 aula2 aula3 - aula residuos - ubicacion b1 b2 b3 - bolsa)
  (:init
    (en r1 residuos) (robot-libre r1)
    (adyacente aula1 aula2) (adyacente aula2 aula1)
    (adyacente aula2 aula3) (adyacente aula3 aula2)
    (adyacente aula3 residuos) (adyacente residuos aula3)
    (sucia aula1) (sucia aula2) (sucia aula3)
    (bolsa-en b1 aula1) (bolsa-en b2 aula2) (bolsa-en b3 aula3)
  )
  (:goal (and (limpia aula1) (limpia aula2) (limpia aula3) 
              (bolsa-depositada b1) (bolsa-depositada b2) (bolsa-depositada b3)))
)